### PR TITLE
Several bug fixes (credit: iborvs)

### PR DESCRIPTION
**Pull request by KCFindstr**
I cherrypicked some of @iborvs 's [fixes](https://github.com/iborvs/ShinColle), including:
- Apply enchantments to aircraft
- zh_cn language file
- Add 18.11-inch Tripple Cannon
- Fix a bug that duplicates food (kanmusu not consuming items correctly)

There are two commits in @iborvs 's fork that confuses me, therefore not included in this PR:
- Improve LOS (56087fb76decbcecfe0be6625d339cff84bde48b)
- Fix attack emoticon (e4c1100fe4e7d1fcbfb474b05897f1ff4809c258)

Also fixed some styling problems, mostly mixed spaces and tabs.

Could you leave this PR open for a week or so before merging? So that @iborvs might be able to see this. I didn't find a way to communicate directly and thus I can only hope the mentions in this PR work.

### CODE REVIEW

**Comment by KirikaAetheria** [comment]
Hey again, good work on picking through iborvs's fixes. Given how long it's been since he was last active it's unlikely he'll see these mentions anytime soon, though

One suggestion I have is that you add a line to the en_us.lang file as well for the Yamato cannon, so that english players can see the weapon's name as well. Although, you'll probably want to name it 46cm Triple Gun Mount there since this one is an actual kanmusu weapon, unlike all the other cannons which are abyssal weapons (maybe iborvs changed it because he thought cannons were supposed to be labelled in inches, since that's how all the others were named too?)

As for the two commits which you haven't included, I'll open eclipse and see if I can make sense of them. I've spent a few months dissecting this mod in an attempt at porting it to 1.16 (currently shelved), so hopefully I'll be of some help in this matter. Will get back to you later

**Comment by KirikaAetheria** [comment]
Alright, having given it a quick look, this is what I'm seeing:

- 56087fb seems to basically be a bruteforce approach to trying to correct the target acquisition bug you handled in 1d9f4a2. iborvs added a whole new fireControl() method which was called every 1.6 seconds, and its contents are pretty much a copy of updateTask()'s lines which dealt with targeting enemies, although with some checks removed for even more forcefulness. This seems to be an experimental fix, as iborvs added a lot of debug messages throughout the file to try and understand whether the kanmusu was actually able to identify enemies at all. This approach was likely only marginally more effective at finding targets by making sure the targeting cycle was called more often, especially given that the root cause of switching .expand to .grow wasn't solved.
- e4c1100 was a fix to the copying of updateTask()'s lines which was done in 56087fb. When copying all the required lines for the targeting bruteforce approach, it seems ibovrs left one out which caused the kanmusu to look at the enemy she was attacking, meaning that if the kanmusu attacked while in the fireControl() method, she wouldn't look at the target. So it seems it was actually a fix for looking while attacking, not for the attack emoticon effects (although google translate and deepl did nothing to help clear this confusion, all I got was "attack expression correction" as well).

As such, I believe that, assuming your previous commit in 1d9f4a2 managed to fix targeting in a way that mirrors how it worked in 1.10.2, there's no benefit to including these fixes, or rather, there's a good chance it might actually be somewhat detrimental.

That's all I've got, hopefully it was of some help

**Comment by KCFindstr** [comment]
> That's all I've got, hopefully it was of some help

Thank you a lot, that's really helpful! I've added 46cm Triple Gun Mount to all language files and revised the translation in zh_cn.

> As such, I believe that, assuming your previous commit in 1d9f4a2 managed to fix targeting in a way that mirrors how it worked in 1.10.2, there's no benefit to including these fixes, or rather, there's a good chance it might actually be somewhat detrimental.

I can't say my fix exactly mirrors how it worked in 1.10.2 but it definitely helped the kanmusu to target nearby enemies correctly. I haven't played this mod in mc 1.10, but I don't notice any strange behaviors on targeting enemies after this fix.


> As for the two commits which you haven't included, I'll open eclipse and see if I can make sense of them. I've spent a few months dissecting this mod in an attempt at porting it to 1.16 (currently shelved), so hopefully I'll be of some help in this matter. Will get back to you later

That's awesome! I'm happy to help if you want to port this mod to later minecraft versions, but I don't have experience porting minecraft mods so it might take me some time to learn. If you have a repo, do you want to add me as a collaborator so that we can work together?

**Comment by KirikaAetheria** [comment]
First of all I'd just like to make a correction in regards to what I said earlier. I checked 56087fb a bit more carefully afterwards and noticed I skipped over some very important lines. iborvs actually made some changes in the findTarget() method, replacing this line

`List<EntityLivingBase> list1 = this.host2.world.getEntitiesWithinAABB(EntityLivingBase.class, this.host2.getEntityBoundingBox().expand(this.range * 0.9D, this.range * 0.6D, this.range * 0.9D), this.targetSelector);`

with this set of lines

`AxisAlignedBB fireRange = this.host2.getEntityBoundingBox().expand(this.range * 0.9D, this.range * 0.6D, this.range * 0.9D);`
`fireRange =  fireRange.expand(this.range * -0.9D, this.range * -0.6D, this.range * -0.9D);`
`List<EntityLivingBase> list1 = this.host2.world.getEntitiesWithinAABB(EntityLivingBase.class, fireRange, this.targetSelector);`

which means he did notice the bounding box only extended towards the positive side of each axis, and corrected the issue despite being unaware that .grow existed. However, I'd still maintain that there was likely no need to implement fireControl() and all its related changes, especially since you've already playtested your fix and confirmed the bug was solved. I did want to clear that up though, as he managed to reach a valid solution to this issue as well.

>
> Thank you a lot, that's really helpful! I've added 46cm Triple Gun Mount to all language files and revised the translation in zh_cn. 
>
Glad I could help, but it was nothing. Rather, thank you for looking into all these long-standing issues.

>
> I can't say my fix exactly mirrors how it worked in 1.10.2 but it definitely helped the kanmusu to target nearby enemies correctly. I haven't played this mod in mc 1.10, but I don't notice any strange behaviors on targeting enemies after this fix.
>
I hadn't played the 1.10.2 version either, but there were quite a few complaints about this targeting bug appearing after the 1.12.2 port. Which comes as no surprise, as this mod touches on nearly every single facet of minecraft modding... Regardless, if you've tried it out already, it's probably safe to say you've managed to solve it completely.
 
---

> 
> That's awesome! I'm happy to help if you want to port this mod to later minecraft versions, but I don't have experience porting minecraft mods so it might take me some time to learn. If you have a repo, do you want to add me as a collaborator so that we can work together?
>
I haven't added anything to my forked repository of shincolle since I wanted to at least get the code up to a level where it would compile, which, well... there's a good reason why that attempt is currently shelved. I am very thankful that you've offered of course, and if I was working on it actively I'd take you up on your offer immediately, but after I realised just what porting this mod would entail, my motivation died on the spot.

The issue is, when I said above that this mod touches nearly every facet of minecraft modding, it wasn't an exaggeration. AI routines, 3D models, animations for those models, effects, mob spawning, loot tables, world generation, GUIs, new blocks and their accompanying blockstates, server packets, etc etc etc. It's a horribly extensive list, and the worst part is that after 4 major minecraft versions, and all respective forge updates, the methods with which you'd implement a great deal of these features have changed -completely- or even been replaced altogether, to the point where one would need to relearn the process of modding in each of these systems, and then entirely recreate each feature from the ground up.

It's a simply cataclysmic amount of work, to the point where it feels insurmountable. Of course, that's likely in part because prior to working on this for about 4 months I was a complete beginner too, and even now I'm inexperienced at best; I'm sure a veteran modder who knows the ins and outs of 1.16 modding would laugh at me for what I just said. However, with no real tutorials out there, the only real way forward I can see is an extraordinarily painful series of trial and error for each and every one of those systems that need to be remade. Add some general clean-up and restructuring of a few convoluted bits of shincolle on top of all this, and I can't imagine it'd take less than 6-8 months of nonstop work. So yeah, pretty damn overwhelming. Which isn't to say I've completely given up on it, but it's one of those things which need some real motivation to get started on.

I'd rather not keep talking about it here since it'd turn this pull request into an off-topic discussion, but if you're interested in knowing more about what the 1.16 port would entail/want to discuss something about it in more detail, and also if you want to bounce ideas on some 1.12.2 bug you might be trying to fix in the future, feel free to contact me. My email is in my profile, or if you'd rather do it in real time you can also email me a discord tag and I'll add you.

**Comment by Cappycot** [comment]
Let me know if we're good to merge.

**Comment by KCFindstr** [comment]
Sorry for keep you waiting - I believe it's good to merge now

**Pull request merged**
