### PR TITLE
Fix NullPointerException when cooking

### PR DESCRIPTION
**Pull request by KCFindstr**
A `NullPointerException` arises when instructing a Kanmusu to cook. Stacktrace:
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.lulan.shincolle.utility.InventoryHelper.getSlotsFromSide(InventoryHelper.java:914)
	at com.lulan.shincolle.utility.TaskHelper.onUpdateCooking(TaskHelper.java:657)
	at com.lulan.shincolle.utility.TaskHelper.onUpdateTask(TaskHelper.java:89)
	at com.lulan.shincolle.entity.BasicEntityShip.func_70636_d(BasicEntityShip.java:2075)
	at com.lulan.shincolle.entity.cruiser.EntityCANe.func_70636_d(EntityCANe.java:150)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.lulan.shincolle.entity.BasicEntityShip.func_70071_h_(BasicEntityShip.java:1856)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

It seems that when porting to minecraft 1.12, `itemStack.isEmpty()` is preferred over `itemStack == null`. However, a null pointer is passed in intentionally which breaks the code:
https://github.com/Cappycot/ShinColle/blob/b648ef5e301fa21d796b73da0fa5b4c2b3bdfb37/src/main/java/com/lulan/shincolle/utility/TaskHelper.java#L657 .

This pull request fixes this bug and adds mclib debug dependency.

### CODE REVIEW

**Comment by Cappycot** [comment]
I haven't looked at Minecraft code in ages. This should be good to go - I'll merge in the next couple of days.

**Comment by KCFindstr** [comment]
Thank you! Btw, do you have any plan to merge your fork into the original repo which does not have 1.12 support?

**Comment by Cappycot** [comment]
Probably not since it contains commits from two other users.

**Comment by Cappycot** [comment]
I'll go ahead and merge. I'll try to build a new jar later this week.

**Pull request merged**
