### PR TITLE
Fix: Ship entities not showing up in Abyssal Logbook

### PR DESCRIPTION
**Pull request by KCFindstr**
The ship entities do not show up in Abyssal Logbook even after opening their GUI.

It occurs to me that this is due to the shincolle namespace preceeding item names. The original code seems to be looking for `EntityHeavyCruiserNe` while it is supposed to look for `shincolle:entityheavycruiserne`. Therefore, the returned entity is always null and the logbook fails to render the content.

I've switch `EntityList.getClassFromName(String)` to `EntityList.getClass(ResourceLocation)` for compatibility. This fixes this bug as expected.

There are blank space fixes done by my IDE, and I also fix some typing problems that show up as warnings on my side. Please pay attention to line 2226-2247 in `GuiDesk.java` because that's where the fix takes place. I also changed some of the name strings from `namespace.name` to `namespace:name`, but I'm not sure if that's correct per context. I assume there was an update in minecraft that changed `.` to `:` in namespace definitions? If not, I can revert the name changes.

### CODE REVIEW

**Comment by KirikaAetheria** [comment]
hey there, just dropping by since you've been working on these fixes lately

if you're planning to patch up some more of these bugs in the future, you might want to check out [iborvs's fork](https://github.com/iborvs/ShinColle) before you go looking into the code on your own, as he managed to fix a couple of bugs a while ago, this one included (at least according to the changelog he posted, I haven't actually tested it myself). so depending on what you're trying to fix, it might save you a bit of time to check out how he went about it

regardless, good job on all the stuff you've managed to fix so far. it's nice seeing this mod getting some love

**Comment by KCFindstr** [comment]
> hey there, just dropping by since you've been working on these fixes lately
> 
> if you're planning to patch up some more of these bugs in the future, you might want to check out [iborvs's fork](https://github.com/iborvs/ShinColle) before you go looking into the code on your own, as he managed to fix a couple of bugs a while ago, this one included (at least according to the changelog he posted, I haven't actually tested it myself). so depending on what you're trying to fix, it might save you a bit of time to check out how he went about it
> 
> regardless, good job on all the stuff you've managed to fix so far. it's nice seeing this mod getting some love

Thanks, I checked out iborvs's fork and we seem to be tackling these issues in different ways. It's nice to see that some other bugs I haven't discovered have been fixed. The bug that caused the server to crash during cooking does not seem to have been fixed though.

I think it'll be great if @iborvs can open a PR to cherry pick some of his fixes? The forks of this mod are already confusing since they branch out a lot and it is preferable to have a centralized repo.

**Comment by Cappycot** [comment]
I wish I had the time at the moment to help, but I'm doing dev work for another game rn. Once that's squared away I might pick up Minecraft modding again. In the meantime, I'll just merge these requests.

**Comment by KirikaAetheria** [comment]
> 
> 
> I'm doing dev work for another game rn.

You're officially working on from the depths? That's outstanding, that game's great. Glad the devs noticed your work on the camera mod and got you onboard.

Also don't worry about shincolle, I can't speak for KCFindstr but I think we understand that this mod was probably not something you'd feel like picking back up. Rather, it's pretty great you're still checking in and merging requests after all this time; can't imagine that many people would bother.

**Pull request merged**
